#!/bin/bash

DIR_HOME="/home/nest/nest"
DIR_CONFIG="${DIR_HOME}/config.d"

if [ "$1" == "" ]; then
	echo "Usage : nest { done | help | reset }"
fi

if [ "$1" == "trainee" ]; then
	if [ "$2" == "" ]; then
		echo "Usage : nest trainee [ NUMBER ]"
	else
		if [ ! -d "$DIR_HOME/trainee.d" ]; then
			mkdir "$DIR_HOME/trainee.d"
		fi

		for i in $(seq -f "%02g" 1 $2)
		do
			mkdir "$DIR_HOME/trainee.d/stduser$i"
		done
	fi
	exit 0
fi

if [ "$1" == "check" ]; then
	while true
	do
		clear
		n=0
		for i in $(ls $DIR_HOME/trainee.d)
		do
			if [ -f "$DIR_HOME/trainee.d/$i/done" ]; then
				EMOJI="\033[47;30m^_^\033[0m"
			elif [ -f "$DIR_HOME/trainee.d/$i/help" ]; then
				EMOJI="\033[43;30mT.T\033[0m"
			else
				EMOJI="-.-"
			fi

			if [ "$n" -eq  9 ]; then
				echo -e "$i($EMOJI)"
				n=0
			else
				echo -e -n "$i($EMOJI) "
				n=$((n + 1))
			fi
		done
		sleep 5
	done
fi

if [ "$1" == "clear" ]; then
	for i in $(ls $DIR_HOME/trainee.d)
	do
		echo "rm -f $DIR_HOME/trainee.d/$i/*"
		rm -f "$DIR_HOME/trainee.d/$i/"*
	done
fi


if [ "$1" == "setup" ]; then
	echo -n "Input server IP : "
	read val
	server_ip=val
	echo $val > $DIR_CONFIG/server

	echo ""
	echo "ssh-keygen"
	ssh-keygen

	echo ""
	echo "ssh-copy-id"
	ssh-copy-id nest@"$server_ip"

	echo -n "Input trainee name : "
	read val
	trainee_name=$val
	echo $val > $DIR_CONFIG/trainee
fi
