#!/bin/bash

DIR_HOME="/home/nest/nest"
DIR_CONFIG="${DIR_HOME}/config.d"
SERVER=$(cat "${DIR_CONFIG}/server")
TRAINEE=$(cat "${DIR_CONFIG}/trainee")

if [ "$1" == "" ]; then
	echo "Usage : nest { done | help | reset | status }"
fi

if [ "$1" == "status" ]; then
	result=$(ssh nest@$SERVER ls $DIR_HOME/trainee.d/$TRAINEE)
	if [ "$result" == "" ]; then
		result="none"
	fi
	echo "$result"
fi

if [ "$1" == "done" ]; then
	ssh nest@$SERVER rm -f $DIR_HOME/trainee.d/$TRAINEE/*
	ssh nest@$SERVER touch $DIR_HOME/trainee.d/$TRAINEE/done
fi

if [ "$1" == "help" ]; then
	ssh nest@$SERVER rm -f $DIR_HOME/trainee.d/$TRAINEE/*
	ssh nest@$SERVER touch $DIR_HOME/trainee.d/$TRAINEE/help
fi

if [ "$1" == "reset" ]; then
	ssh nest@$SERVER rm -f $DIR_HOME/trainee.d/$TRAINEE/*
fi

if [ "$1" == "addlink" ]; then
	ln -s "${DIR_HOME}/nest" /usr/local/bin/nest
fi

if [ "$1" == "trainee" ]; then
	if [ "$2" == "" ]; then
		echo "Usage : nest trainee [ NUMBER ]"
	else
		if [ ! -d "$DIR_HOME/trainee.d" ]; then
			mkdir "$DIR_HOME/trainee.d"
		fi

		for i in $(seq -f "%02g" 1 $2)
		do
			mkdir "$DIR_HOME/trainee.d/Estduser$i"
		done
	fi
	exit 0
fi

cnt_trainee=$(ls $DIR_HOME/trainee.d | wc -l)
if [ "$1" == "check" ]; then
	while true
	do
		clear
		num=1
		tnum=1
		for i in $(ls $DIR_HOME/trainee.d)
		do
			if [ -f "$DIR_HOME/trainee.d/$i/done" ]; then
				EMOJI="\033[47;30m^_^\033[0m"
			elif [ -f "$DIR_HOME/trainee.d/$i/help" ]; then
				EMOJI="\033[43;30mT.T\033[0m"
			else
				EMOJI="-.-"
			fi

			if [ "$num" -eq  5 -a "$tnum" != "$cnt_trainee" ]; then
				echo -e "$i($EMOJI)"
				num=1
			else
				echo -e -n "$i($EMOJI) "
				num=$((num + 1))
			fi
			tnum=$((tnum + 1))
		done
		sleep 3
	done
fi

if [ "$1" == "clear" ]; then
	for i in $(ls $DIR_HOME/trainee.d)
	do
		#echo "rm -f $DIR_HOME/trainee.d/$i/*"
		rm -f "$DIR_HOME/trainee.d/$i/"*
	done
fi


if [ "$1" == "setup" ]; then
	echo -n "Input server IP : "
	read val
	server_ip="$val"
	echo $val > $DIR_CONFIG/server

	if [ ! -f /root/.ssh/id_rsa.pub ]; then
		echo ""
		echo "ssh-keygen"
		ssh-keygen
	fi

	echo ""
	echo "ssh-copy-id nest@$server_ip"
	ssh-copy-id nest@"$server_ip"

	echo -n "Input trainee name : "
	read val
	trainee_name="$val"
	echo $val > $DIR_CONFIG/trainee
fi
